### ISSUE TITLE
Add as_raw_fd to WpaController

### ISSUE THREAD

**Issue by elham-Nikooie** [sauyon/wpa-ctrl-rs#12]
I need to read wpa socket in a separate thread to get the unsolicited messages and react based on the received events!
For doing that I need to read from the file descriptor of wpa_controller!

```
impl WpaController {
    pub fn as_raw_fd(&self) -> std::os::unix::io::RawFd {
        self.socket.as_raw_fd()
    }
}
```
Then in my code I can just do:
`let fd = wpa_controller.as_raw_fd();
`
and start reading that by `recvfrom(fd, &mut buffer)`

**Comment by spease** [comment]
Did you mean to close this? Is this just the same as the AsRawFd PR?

- Steven
